"""empty message

Revision ID: 01b183ea6bd1
Revises: 038b4eefddda
Create Date: 2024-05-30 14:39:49.676510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01b183ea6bd1'
down_revision: Union[str, None] = '038b4eefddda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Bron', 'Amount_day')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Bron', sa.Column('Amount_day', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
