"""empty message

Revision ID: 038b4eefddda
Revises: 56d39f28fe9c
Create Date: 2024-05-30 14:36:32.786613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '038b4eefddda'
down_revision: Union[str, None] = '56d39f28fe9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Bron', sa.Column('Checkout_date', sa.String(length=255), nullable=False))
    op.add_column('Bron', sa.Column('Checkin_date', sa.String(length=255), nullable=False))
    op.drop_column('Bron', 'Date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Bron', sa.Column('Date', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('Bron', 'Checkin_date')
    op.drop_column('Bron', 'Checkout_date')
    # ### end Alembic commands ###
