"""empty message

Revision ID: 049fc8177511
Revises: 6ec52b4cab8c
Create Date: 2024-05-30 15:06:27.451142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '049fc8177511'
down_revision: Union[str, None] = '6ec52b4cab8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Bron', sa.Column('Code', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Bron', 'Code')
    # ### end Alembic commands ###
