"""empty message

Revision ID: 169ccf60a7bf
Revises: a9a0cf8a1d0f
Create Date: 2024-05-14 15:32:28.118455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '169ccf60a7bf'
down_revision: Union[str, None] = 'a9a0cf8a1d0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
