"""empty message

Revision ID: 41ed4befc2a1
Revises: 169ccf60a7bf
Create Date: 2024-05-23 14:55:22.595607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41ed4befc2a1'
down_revision: Union[str, None] = '169ccf60a7bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Black_List',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_User', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_User'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Black_List')
    # ### end Alembic commands ###
