"""empty message

Revision ID: 4f6d24afa6db
Revises: 520bdc09c57d
Create Date: 2024-05-04 12:55:31.477044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f6d24afa6db'
down_revision: Union[str, None] = '520bdc09c57d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Order', sa.Column('Code', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Order', 'Code')
    # ### end Alembic commands ###
