"""empty message

Revision ID: 520bdc09c57d
Revises: 87ccd1458756
Create Date: 2024-05-03 21:25:05.895051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '520bdc09c57d'
down_revision: Union[str, None] = '87ccd1458756'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Bron_fk_Status_fkey', 'Bron', type_='foreignkey')
    op.drop_column('Bron', 'fk_Status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Bron', sa.Column('fk_Status', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('Bron_fk_Status_fkey', 'Bron', 'Bron_Status', ['fk_Status'], ['id'])
    # ### end Alembic commands ###
