"""empty message

Revision ID: 56d39f28fe9c
Revises: 881902b13361
Create Date: 2024-05-30 14:10:14.879874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56d39f28fe9c'
down_revision: Union[str, None] = '881902b13361'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('BronStatus', sa.Column('fk_Bron', sa.Integer(), nullable=False))
    op.drop_constraint('BronStatus_fk_Order_fkey', 'BronStatus', type_='foreignkey')
    op.create_foreign_key(None, 'BronStatus', 'Bron', ['fk_Bron'], ['id'])
    op.drop_column('BronStatus', 'fk_Order')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('BronStatus', sa.Column('fk_Order', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'BronStatus', type_='foreignkey')
    op.create_foreign_key('BronStatus_fk_Order_fkey', 'BronStatus', 'Bron', ['fk_Order'], ['id'])
    op.drop_column('BronStatus', 'fk_Bron')
    # ### end Alembic commands ###
