"""empty message

Revision ID: 65b86b6ce26a
Revises: 94aa848a2e7b
Create Date: 2024-05-14 15:18:48.355686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65b86b6ce26a'
down_revision: Union[str, None] = '94aa848a2e7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('BronStatus', sa.Column('fk_Status', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'BronStatus', 'Status', ['fk_Status'], ['id'])
    op.drop_column('BronStatus', 'Status')
    op.add_column('OrderStatus', sa.Column('fk_Status', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'OrderStatus', 'Status', ['fk_Status'], ['id'])
    op.drop_column('OrderStatus', 'Status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('OrderStatus', sa.Column('Status', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'OrderStatus', type_='foreignkey')
    op.drop_column('OrderStatus', 'fk_Status')
    op.add_column('BronStatus', sa.Column('Status', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'BronStatus', type_='foreignkey')
    op.drop_column('BronStatus', 'fk_Status')
    op.drop_table('Status')
    # ### end Alembic commands ###
