"""empty message

Revision ID: 8237d8d93815
Revises: d100689106f1
Create Date: 2024-05-03 21:11:05.665144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8237d8d93815'
down_revision: Union[str, None] = 'd100689106f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Changes_Status_Bron',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_Order', sa.Integer(), nullable=False),
    sa.Column('fk_Status', sa.Integer(), nullable=False),
    sa.Column('Time', sa.Time(), nullable=False),
    sa.Column('Date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['fk_Order'], ['Bron.id'], ),
    sa.ForeignKeyConstraint(['fk_Status'], ['Bron_Status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Changes_Status_Order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_Order', sa.Integer(), nullable=False),
    sa.Column('fk_Status', sa.Integer(), nullable=False),
    sa.Column('Time', sa.Time(), nullable=False),
    sa.Column('Date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['fk_Order'], ['Order.id'], ),
    sa.ForeignKeyConstraint(['fk_Status'], ['Order_Status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Changes_Status')
    op.add_column('Order', sa.Column('Date', sa.Date(), nullable=False))
    op.add_column('Order', sa.Column('Price', sa.Integer(), nullable=False))
    op.drop_column('Order', 'Name')
    op.add_column('Order_List', sa.Column('fk_Order', sa.Integer(), nullable=False))
    op.drop_constraint('Order_List_fk_User_fkey', 'Order_List', type_='foreignkey')
    op.create_foreign_key(None, 'Order_List', 'Order', ['fk_Order'], ['id'])
    op.drop_column('Order_List', 'fk_User')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Order_List', sa.Column('fk_User', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Order_List', type_='foreignkey')
    op.create_foreign_key('Order_List_fk_User_fkey', 'Order_List', 'Users', ['fk_User'], ['id'])
    op.drop_column('Order_List', 'fk_Order')
    op.add_column('Order', sa.Column('Name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('Order', 'Price')
    op.drop_column('Order', 'Date')
    op.create_table('Changes_Status',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Changes_Status_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('fk_Order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fk_Status', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['fk_Order'], ['Order.id'], name='Changes_Status_fk_Order_fkey'),
    sa.ForeignKeyConstraint(['fk_Status'], ['Order_Status.id'], name='Changes_Status_fk_Status_fkey'),
    sa.PrimaryKeyConstraint('id', name='Changes_Status_pkey')
    )
    op.drop_table('Changes_Status_Order')
    op.drop_table('Changes_Status_Bron')
    # ### end Alembic commands ###
