"""empty message

Revision ID: 87ccd1458756
Revises: 8237d8d93815
Create Date: 2024-05-03 21:17:01.447366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87ccd1458756'
down_revision: Union[str, None] = '8237d8d93815'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Bron', sa.Column('Price', sa.Integer(), nullable=False))
    op.add_column('Rooms', sa.Column('Price_Day', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Rooms', 'Price_Day')
    op.drop_column('Bron', 'Price')
    # ### end Alembic commands ###
