"""empty message

Revision ID: 975d34c898e1
Revises: 049fc8177511
Create Date: 2024-05-30 15:33:45.508691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '975d34c898e1'
down_revision: Union[str, None] = '049fc8177511'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Bron', 'Time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Bron', sa.Column('Time', postgresql.TIME(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
