"""empty message

Revision ID: a9a0cf8a1d0f
Revises: 65b86b6ce26a
Create Date: 2024-05-14 15:26:02.089460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9a0cf8a1d0f'
down_revision: Union[str, None] = '65b86b6ce26a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Order', 'Date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Order', sa.Column('Date', sa.DATE(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
