"""Add new column to table

Revision ID: fb48d811974e
Revises: 975d34c898e1
Create Date: 2024-06-16 12:57:29.392827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb48d811974e'
down_revision: Union[str, None] = '975d34c898e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Dish', sa.Column('Image', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Dish', 'Image')
    # ### end Alembic commands ###
