"""empty message

Revision ID: fcf7b456e28e
Revises: 953f9a5bd149
Create Date: 2024-05-06 15:13:02.751930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcf7b456e28e'
down_revision: Union[str, None] = '953f9a5bd149'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ShoppingCart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_User', sa.Integer(), nullable=False),
    sa.Column('Price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_User'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Basket')
    op.add_column('ShoppingCartList', sa.Column('fk_ShoppingCart', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'ShoppingCartList', 'ShoppingCart', ['fk_ShoppingCart'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ShoppingCartList', type_='foreignkey')
    op.drop_column('ShoppingCartList', 'fk_ShoppingCart')
    op.create_table('Basket',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Basket_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('fk_User', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['fk_User'], ['Users.id'], name='Basket_fk_User_fkey'),
    sa.PrimaryKeyConstraint('id', name='Basket_pkey')
    )
    op.drop_table('ShoppingCart')
    # ### end Alembic commands ###
